vim.keymap.set('n', '<c-n>', ':tabnew <CR>')
vim.keymap.set('n', 'n', 'nzz')
vim.keymap.set('n', 'N', 'Nzz')
vim.keymap.set('n', '<CR>', 'o<Esc>')
--vim.keymap.set('i', 'jj', '<ESC>')
--vim.keymap.set('i', '<esc>', '<nop>')
