# -*- conf -*-
shell=/usr/bin/zsh
term=foot 

app-id=foot 
title=foot
locked-title=no

font=Iosevka Nerd Font:size=14

[main]
# Resolves the appearance of the "%" character in a new Foot terminal window
# when using zsh as default shell
initial-window-size-chars=100x30

[url]
launch=xdg-open ${url}

[cursor]
style=block
unfocused-style=hollow
blink=no

[colors-dark]
# It is necessary to set the cursor's foreground and background colors
# to some  values; otherwise, they will always be inverted, 
# which can cause issues in Vim when matching pairs
cursor=111111 cccccc
# This config uses default theme which is(in version 1.25.0) "starlight"
