# -*- conf -*-
shell=/bin/bash
term=foot 

app-id=foot 
title=foot
locked-title=no

font=Iosevka Nerd Font:size=15

[url]
launch=xdg-open ${url}

[cursor]
style=block
unfocused-style=hollow
blink=no

[colors]
# It is necessary to set the cursor's foreground and background colors
# to some  values; otherwise, they will always be inverted, 
# which can cause issues in Vim when matching pairs
cursor=111111 cccccc
# This config uses default theme which is(in version 1.25.0) "starlight"
