
abbr -a -U v 'nvim'
abbr -a -U grep 'grep --color=auto'
abbr -a -U fgrep 'fgrep --color=auto'
abbr -a -U egrep 'egrep --color=auto'
abbr -a -U ls 'exa --oneline --icons' #"exa" is version of "ls" rewritten in Rust
abbr -a -U ll 'exa -al --icons'
abbr -a -U myip 'curl ifconfig.co'
abbr -a -U tftp 'atftp'
abbr -a -U suspend 'sudo systemctl suspend'
abbr -a -U homepi 'ssh -p 6435 mark@192.168.0.100 -i ~/.ssh/id_ed25519'
abbr -a -U weather 'curl wttr.in'
abbr -a -U rsync 'rsync -av --info=progress2 --info=name0'
abbr -a -U fd 'fd --hidden'
abbr -a -U rg 'rg --hidden'
abbr -a -U mkdir 'mkdir -p'
abbr -a -U alacrittycfg 'nvim ~/.dotfiles/.config/alacritty/alacritty.yml'
abbr -a -U nvimcfg 'nvim ~/.dotfiles/.config/nvim/init.vim'
abbr -a -U qtilecfg 'nvim ~/.dotfiles/.config/qtile/config.py'
abbr -a -U picomcfg 'nvim ~/.dotfiles/.config/picom/picom.conf'
abbr -a -U myip 'curl ifconfig.co'
abbr -a -U telnet 'rlwrap nc'
abbr -a -U office365-totp 'ph show Novelic/Office365 | grep --color=auto -Po "(?<=OTP\sCode:\s).+" | xclip -i | xclip -o'
abbr -a -U ef 'find ./ | fzf -e -x | xargs -r -o nvim'
abbr -a -U mntnextcloud 'rclone mount --daemon nextcloud:/ /mnt/Nextcloud'
abbr -a -U mnthomepi 'sshfs homepi:/home/mark /mnt/homepi'
abbr -a -U mntwindows 'sshfs windows:/C: /mnt/windows'
abbr -a -U notes 'vim ~/Sync/Notes/'
abbr -a -U vpn-up 'wg-quick up homepi-wg'
abbr -a -U vpn-down 'wg-quick down homepi-wg'
abbr -a -U jd 'cd $(find . -type d -print | fzf)'
abbr -a -U p 'sudo pacman'
abbr -a -U pqs 'sudo pacamn -Qs'
abbr -a -U pss 'sudo pacman -Ss'
abbr -a -U psy 'sudo pacman -Sy'
abbr -a -U psyu 'sudo pacman -Syu'
abbr -a -U prns 'sudo pacman -Rns'
abbr -a -U pscc 'sudo pacman -Scc'
abbr -a -U gd 'git diff'
abbr -a -U gs 'git status'
abbr -a -U gaa 'git add .'
abbr -a -U ptc05_server 'ssh matija@192.168.35.30'
abbr -a -U ptc05 'rlwrap nc 192.168.0.10 2001'
abbr -a -U ptc05_build 'docker run --rm -v ~/.ssh/:/root/.ssh/ -v $PWD:/root/project dryodon/stm32:1.1.0 bash -c "cd /root/project; make clean all"'
abbr -a -U flash_ptc05 'STM32_Programmer_CLI -c port=swd freq=8000 -d ~/Melexis/PTC05_PXI/Release-NoBL/PTC05_DEV_NOBL.hex -rst'
abbr -a -U flash_ptc05_btl 'STM32_Programmer_CLI -c port=swd freq=1 -d ~/Melexis/PTC05_Bootloader-0.6.0.hex -rst'
abbr -a -U mlxdev 'cd ~/Melexis/PTC05_PXI & vim'
