preload = /home/ary/Pictures/wallpapers/4k/blue_waves_wallpaper.png
preload = /home/ary/Pictures/wallpapers/mountains_over_sea.jpeg
wallpaper = ,/home/ary/Pictures/wallpapers/4k/blue_waves_wallpaper.png
#wallpaper = ,/home/ary/Pictures/wallpapers/mountains_over_sea.jpeg
