require('plugins')
require('gitsigns-conf')
require('keymaps')
require('telescope-conf')
require('indent-blankline')
require('treesitter')
require('treesitter-textobjects')
require('lualine-conf')
-- require('nvim-tree-conf')
require('autopairs-conf')
require('onedark-conf')
require('tokyonight-conf')
require('base-settings')
require('catppuccin')
require('twilight-conf')
require('noice-conf')
-- require('mini.animate').setup()
require('flash').setup()
require('lsp-zero-conf')
