require("plugins")


require("gitsigns-conf")
require("keymaps")
require("telescope-conf")
require("indent-blankline")
require("treesitter")
require("treesitter-textobjects")
require("treesitter-context-conf")
require("lualine-conf")
require("autopairs-conf")
require("onedark-conf")
require("tokyonight-conf")
require("base-settings")
require("catppuccin")
require("twilight-conf")
-- require("noice-conf")
require("flash").setup()
require("lsp-zero-conf")
require("bufferline-conf")

